EnabledChannels:                        #channels where you can use this plugin's commands
    - '*'
Role: "707310286251622492(change this)" #role needed to use commands
UnbanCommand: "!unban"                  #command to unban people
InfoCommand: "!baninfo"                 #command to look up ban info
ShowInfoAfterUnban: true                #shows a persons baninfo after you've unbanned them. Useful in combination with RequireConfirmation
RequireConfirmation: true               #requires a reaction to confirm the unban
DateFormat: "HH:mm dd-MM-yyyy"          #format used by this plugin. see https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html
HeadInInfo: true                        #includes the head of the mc player in the baninfo response
Debug: false                            #if true, console will be spammed with debug info
RemoveUseless: 5                        #removes "can't find", "not linked", "not banned", "more args" and "no perm" messages after a x seconds.
RemoveInfo: 0                           #removes info responses after x seconds