name: DiscordUnban
version: 1.2.0
description: "Enables you to unban people via discord"
author: TheEpicBlock_TEB
main: io.github.theepicblock.discordunban.DiscordUnban
depend: [DiscordSRV]
softdepend: [DKBans,LiteBans]